/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	v1alpha1 "github.com/PalenaAI/langfuse-operator/api/v1alpha1"
	"github.com/PalenaAI/langfuse-operator/internal/resources"
)

const (
	secretHashAnnotation  = "langfuse.palena.ai/secret-hash"
	generatedSecretSuffix = "-generated-secrets"
	alphanumericCharset   = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
)

// SecretController reconciles Secrets for LangfuseInstance objects.
type SecretController struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=core,resources=secrets,verbs=get;list;watch;create;update;patch
// +kubebuilder:rbac:groups=langfuse.palena.ai,resources=langfuseinstances,verbs=get;list;watch
// +kubebuilder:rbac:groups=langfuse.palena.ai,resources=langfuseinstances/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;patch

func (r *SecretController) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := logf.FromContext(ctx)

	// 1. Fetch the LangfuseInstance
	instance := &v1alpha1.LangfuseInstance{}
	if err := r.Get(ctx, req.NamespacedName, instance); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("fetching LangfuseInstance: %w", err)
	}

	// The secret controller patches the Deployment's pod template — if the
	// CR is being deleted, those patches fight GC and resurrect the workload.
	if !instance.DeletionTimestamp.IsZero() {
		return ctrl.Result{}, nil
	}

	original := instance.DeepCopy()

	// 2. Auto-generate secrets if enabled (default true)
	if autoGenerateEnabled(instance) {
		secretName := instance.Name + generatedSecretSuffix
		if err := r.ensureGeneratedSecret(ctx, instance, secretName); err != nil {
			return ctrl.Result{}, fmt.Errorf("ensuring generated secret: %w", err)
		}

		if instance.Status.Secrets == nil {
			instance.Status.Secrets = &v1alpha1.SecretsStatus{}
		}
		instance.Status.Secrets.AutoGenerated = true
		instance.Status.Secrets.ManagedSecretName = secretName
	}

	// 3. Rotation detection: compute composite hash of all referenced secrets
	rotated := false
	webHash, workerHash, err := r.computeSecretHashes(ctx, instance)
	if err != nil {
		log.Error(err, "failed to compute secret hashes, skipping rotation detection")
	} else {
		for name, hash := range map[string]string{
			resources.WebName(instance):    webHash,
			resources.WorkerName(instance): workerHash,
		} {
			patched, err := r.patchDeploymentSecretHash(ctx, instance, name, hash)
			if err != nil {
				log.Error(err, "failed to patch deployment secret hash", "deployment", name)
				continue
			}
			rotated = rotated || patched
		}
	}

	// Stamp only on an actual rotation. A per-pass metav1.Now() made this write
	// non-idempotent, and every bump fans out to all seven controllers.
	if rotated {
		now := metav1.Now()
		if instance.Status.Secrets == nil {
			instance.Status.Secrets = &v1alpha1.SecretsStatus{}
		}
		instance.Status.Secrets.LastRotationCheck = &now
	}

	if err := updateInstanceStatus(ctx, r.Client, instance, original); err != nil {
		return ctrl.Result{}, fmt.Errorf("updating secret status: %w", err)
	}

	log.Info("reconciled secrets", "instance", instance.Name)
	return ctrl.Result{}, nil
}

// autoGenerateEnabled returns true if auto-generation is enabled (default true).
func autoGenerateEnabled(instance *v1alpha1.LangfuseInstance) bool {
	if instance.Spec.Secrets == nil {
		return true
	}
	if instance.Spec.Secrets.AutoGenerate == nil {
		return true
	}
	if instance.Spec.Secrets.AutoGenerate.Enabled == nil {
		return true
	}
	return *instance.Spec.Secrets.AutoGenerate.Enabled
}

// generatedSecretKey names a key in the auto-generated secret and how to
// produce its value when missing.
type generatedSecretKey struct {
	key string
	gen func() (string, error)
}

// generatedSecretKeys lists every key the operator owns in the auto-generated
// secret. Adding a key here makes it backfill into existing secrets on the
// next reconcile (important for upgrades — e.g. admin-api-key, added in 0.7.0,
// must be created on instances whose secret predates it, or the Langfuse pods
// fail with CreateContainerConfigError on the missing env reference).
func generatedSecretKeys() []generatedSecretKey {
	return []generatedSecretKey{
		{"nextauth-secret", func() (string, error) { return generateSecureRandom(32) }},
		{"salt", func() (string, error) { return generateSecureRandom(16) }},
		{"clickhouse-username", func() (string, error) { return "default", nil }},
		{"clickhouse-password", func() (string, error) { return generateAlphanumeric(24) }},
		{"redis-password", func() (string, error) { return generateAlphanumeric(24) }},
		{"admin-api-key", func() (string, error) { return generateSecureRandom(32) }},
	}
}

// ensureGeneratedSecret creates the auto-generated Secret if absent, and
// backfills any operator-owned keys missing from an existing one.
func (r *SecretController) ensureGeneratedSecret(ctx context.Context, instance *v1alpha1.LangfuseInstance, secretName string) error {
	existing := &corev1.Secret{}
	err := r.Get(ctx, types.NamespacedName{Name: secretName, Namespace: instance.Namespace}, existing)

	switch {
	case err == nil:
		// Secret exists — backfill any keys it is missing.
		added := []string{}
		if existing.Data == nil {
			existing.Data = map[string][]byte{}
		}
		for _, k := range generatedSecretKeys() {
			if _, ok := existing.Data[k.key]; ok {
				continue
			}
			v, genErr := k.gen()
			if genErr != nil {
				return fmt.Errorf("generating %s: %w", k.key, genErr)
			}
			existing.Data[k.key] = []byte(v)
			added = append(added, k.key)
		}
		if len(added) == 0 {
			return nil
		}
		if err := r.Update(ctx, existing); err != nil {
			return fmt.Errorf("backfilling generated secret keys %v: %w", added, err)
		}
		logf.FromContext(ctx).Info("backfilled auto-generated secret keys", "name", secretName, "keys", added)
		return nil
	case !apierrors.IsNotFound(err):
		return fmt.Errorf("checking for existing secret: %w", err)
	}

	// Secret does not exist — create it with all keys.
	data := map[string][]byte{}
	for _, k := range generatedSecretKeys() {
		v, genErr := k.gen()
		if genErr != nil {
			return fmt.Errorf("generating %s: %w", k.key, genErr)
		}
		data[k.key] = []byte(v)
	}

	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName,
			Namespace: instance.Namespace,
			Labels:    resources.CommonLabels(instance, "secrets"),
		},
		Type: corev1.SecretTypeOpaque,
		Data: data,
	}

	if err := controllerutil.SetControllerReference(instance, secret, r.Scheme); err != nil {
		return fmt.Errorf("setting owner reference: %w", err)
	}

	if err := r.Create(ctx, secret); err != nil {
		return fmt.Errorf("creating generated secret: %w", err)
	}

	logf.FromContext(ctx).Info("created auto-generated secret", "name", secretName)
	return nil
}

// collectReferencedSecretNames gathers all Secret names referenced in the spec.
func collectReferencedSecretNames(instance *v1alpha1.LangfuseInstance) []string {
	seen := map[string]struct{}{}

	addRef := func(ref *v1alpha1.SecretKeyRef) {
		if ref != nil {
			seen[ref.Name] = struct{}{}
		}
	}
	addKeysRef := func(ref *v1alpha1.SecretKeysRef) {
		if ref != nil {
			seen[ref.Name] = struct{}{}
		}
	}

	// Auto-generated secret
	seen[instance.Name+generatedSecretSuffix] = struct{}{}

	// Auth
	if instance.Spec.Auth.NextAuthSecret != nil && instance.Spec.Auth.NextAuthSecret.SecretRef != nil {
		addRef(instance.Spec.Auth.NextAuthSecret.SecretRef)
	}
	if instance.Spec.Auth.Salt != nil && instance.Spec.Auth.Salt.SecretRef != nil {
		addRef(instance.Spec.Auth.Salt.SecretRef)
	}
	if instance.Spec.Auth.OIDC != nil {
		addRef(instance.Spec.Auth.OIDC.ClientId)
		addRef(instance.Spec.Auth.OIDC.ClientSecret)
	}
	if instance.Spec.Auth.InitUser != nil {
		addRef(instance.Spec.Auth.InitUser.Password)
	}

	// Database
	if instance.Spec.Database != nil && instance.Spec.Database.External != nil {
		addKeysRef(&instance.Spec.Database.External.SecretRef)
	}

	// ClickHouse
	if instance.Spec.ClickHouse != nil {
		if instance.Spec.ClickHouse.External != nil {
			addKeysRef(&instance.Spec.ClickHouse.External.SecretRef)
		}
		if instance.Spec.ClickHouse.Managed != nil && instance.Spec.ClickHouse.Managed.Auth != nil {
			addKeysRef(instance.Spec.ClickHouse.Managed.Auth.SecretRef)
		}
	}

	// Redis
	if instance.Spec.Redis != nil && instance.Spec.Redis.External != nil {
		addKeysRef(&instance.Spec.Redis.External.SecretRef)
	}

	// BlobStorage
	if instance.Spec.BlobStorage != nil {
		if instance.Spec.BlobStorage.S3 != nil && instance.Spec.BlobStorage.S3.Credentials != nil {
			addKeysRef(&instance.Spec.BlobStorage.S3.Credentials.SecretRef)
		}
		if instance.Spec.BlobStorage.Azure != nil && instance.Spec.BlobStorage.Azure.Credentials != nil {
			addKeysRef(&instance.Spec.BlobStorage.Azure.Credentials.SecretRef)
		}
		if instance.Spec.BlobStorage.GCS != nil && instance.Spec.BlobStorage.GCS.Credentials != nil {
			addKeysRef(&instance.Spec.BlobStorage.GCS.Credentials.SecretRef)
		}
	}

	// LLM
	if instance.Spec.LLM != nil {
		addRef(instance.Spec.LLM.APIKey)
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// computeSecretHashes computes a composite SHA256 hash of all referenced Secrets.
// Returns separate hashes for web and worker components (currently identical since
// both share the same secrets, but kept separate for future component-specific mappings).
func (r *SecretController) computeSecretHashes(ctx context.Context, instance *v1alpha1.LangfuseInstance) (string, string, error) {
	secretNames := collectReferencedSecretNames(instance)

	hasher := sha256.New()
	for _, name := range secretNames {
		secret := &corev1.Secret{}
		if err := r.Get(ctx, types.NamespacedName{Name: name, Namespace: instance.Namespace}, secret); err != nil {
			if apierrors.IsNotFound(err) {
				continue
			}
			return "", "", fmt.Errorf("fetching secret %s: %w", name, err)
		}
		// Hash the secret data in a deterministic order
		keys := make([]string, 0, len(secret.Data))
		for k := range secret.Data {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			hasher.Write([]byte(k))
			hasher.Write(secret.Data[k])
		}
	}

	compositeHash := hex.EncodeToString(hasher.Sum(nil))

	// Both web and worker use the same secrets today. If custom rotation mappings
	// are configured, you'd split the hash per component here.
	return compositeHash, compositeHash, nil
}

// patchDeploymentSecretHash patches the secret hash annotation on a Deployment
// to trigger a rolling restart when secrets change.
// patchDeploymentSecretHash stamps the composite secret hash onto the pod
// template to trigger a rolling restart. It reports whether it patched.
func (r *SecretController) patchDeploymentSecretHash(ctx context.Context, instance *v1alpha1.LangfuseInstance, deployName, newHash string) (bool, error) {
	deploy := &appsv1.Deployment{}
	key := types.NamespacedName{Name: deployName, Namespace: instance.Namespace}
	if err := r.Get(ctx, key, deploy); err != nil {
		if apierrors.IsNotFound(err) {
			return false, nil // Deployment not created yet
		}
		return false, fmt.Errorf("getting deployment %s: %w", deployName, err)
	}

	currentHash := ""
	if deploy.Spec.Template.Annotations != nil {
		currentHash = deploy.Spec.Template.Annotations[secretHashAnnotation]
	}
	if currentHash == newHash {
		return false, nil
	}

	// Patch the pod template annotation to trigger rolling restart
	patch := client.MergeFrom(deploy.DeepCopy())
	if deploy.Spec.Template.Annotations == nil {
		deploy.Spec.Template.Annotations = make(map[string]string)
	}
	deploy.Spec.Template.Annotations[secretHashAnnotation] = newHash

	if err := r.Patch(ctx, deploy, patch); err != nil {
		return false, fmt.Errorf("patching deployment %s: %w", deployName, err)
	}

	logf.FromContext(ctx).Info("patched secret hash annotation", "deployment", deployName, "hash", newHash[:12])
	return true, nil
}

// generateSecureRandom generates a cryptographically secure random hex string.
func generateSecureRandom(length int) (string, error) {
	bytes := make([]byte, length)
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("generating random bytes: %w", err)
	}
	return hex.EncodeToString(bytes), nil
}

// generateAlphanumeric generates a cryptographically secure random alphanumeric string.
func generateAlphanumeric(length int) (string, error) {
	result := make([]byte, length)
	for i := range result {
		b := make([]byte, 1)
		if _, err := rand.Read(b); err != nil {
			return "", fmt.Errorf("generating random byte: %w", err)
		}
		result[i] = alphanumericCharset[int(b[0])%len(alphanumericCharset)]
	}
	return string(result), nil
}

// SetupWithManager sets up the controller with the Manager.
func (r *SecretController) SetupWithManager(mgr ctrl.Manager) error {
	// Only spec changes need to reach this controller; sibling status writes do
	// not. Rotation arrives through the Secret watch below.
	return ctrl.NewControllerManagedBy(mgr).
		For(&v1alpha1.LangfuseInstance{}, builder.WithPredicates(predicate.GenerationChangedPredicate{})).
		Watches(
			&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.findInstancesForSecret),
		).
		Named("secret").
		Complete(r)
}

// findInstancesForSecret maps a Secret event to reconcile requests for
// LangfuseInstances that reference it.
func (r *SecretController) findInstancesForSecret(ctx context.Context, obj client.Object) []reconcile.Request {
	instances := &v1alpha1.LangfuseInstanceList{}
	if err := r.List(ctx, instances, client.InNamespace(obj.GetNamespace())); err != nil {
		logf.FromContext(ctx).Error(err, "failed to list LangfuseInstances for secret mapping")
		return nil
	}

	var requests []reconcile.Request
	secretName := obj.GetName()
	for _, instance := range instances.Items {
		referencedNames := collectReferencedSecretNames(&instance)
		for _, name := range referencedNames {
			if name == secretName {
				requests = append(requests, reconcile.Request{
					NamespacedName: types.NamespacedName{
						Name:      instance.Name,
						Namespace: instance.Namespace,
					},
				})
				break
			}
		}
	}
	return requests
}
